from __future__ import annotations

from typing import Any, Protocol


class WhatsAppProvider(Protocol):
    def provision_instance(
        self,
        instance_name: str,
        token: str,
        webhook_url: str,
        *,
        webhook_token: str,
    ) -> dict[str, Any]: ...
    def get_connection_status(self, binding: dict[str, Any]) -> dict[str, Any]: ...
    def get_qr_code(self, binding: dict[str, Any]) -> dict[str, Any]: ...
    def send_text(self, binding: dict[str, Any], recipient: str, text: str) -> dict[str, Any]: ...
    def send_media(self, binding: dict[str, Any], recipient: str, media: dict[str, Any]) -> dict[str, Any]: ...
    def restart_instance(self, binding: dict[str, Any]) -> dict[str, Any]: ...
    def logout_instance(self, binding: dict[str, Any]) -> dict[str, Any]: ...
    def normalize_webhook(self, payload: dict[str, Any]) -> list[dict[str, Any]]: ...

